# Generated by Django 4.0.1 on 2022-02-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switter', '0003_sweet_re_sweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fave',
            name='sweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faves', to='switter.sweet'),
        ),
    ]
